### ISSUE TITLE
failure unless --collect_memory is passed

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel-bench#109]
```
Traceback (most recent call last):
  File "/home/benjamin/.cache/bazel/_bazel_benjamin/87896217ed058d0cf7ddf603fa041dc4/execroot/__main__/bazel-out/k8-fastbuild/bin/benchmark.runfiles/__main__/benchmark.py", line 695, in <module>
    app.run(main)
  File "/home/benjamin/.cache/bazel/_bazel_benjamin/87896217ed058d0cf7ddf603fa041dc4/execroot/__main__/bazel-out/k8-fastbuild/bin/benchmark.runfiles/third_party_pypi__absl_py_0_9_0/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/benjamin/.cache/bazel/_bazel_benjamin/87896217ed058d0cf7ddf603fa041dc4/execroot/__main__/bazel-out/k8-fastbuild/bin/benchmark.runfiles/third_party_pypi__absl_py_0_9_0/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/benjamin/.cache/bazel/_bazel_benjamin/87896217ed058d0cf7ddf603fa041dc4/execroot/__main__/bazel-out/k8-fastbuild/bin/benchmark.runfiles/__main__/benchmark.py", line 634, in main
    results, args = _run_benchmark(
  File "/home/benjamin/.cache/bazel/_bazel_benjamin/87896217ed058d0cf7ddf603fa041dc4/execroot/__main__/bazel-out/k8-fastbuild/bin/benchmark.runfiles/__main__/benchmark.py", line 322, in _run_benchmark
    _single_run(bazel_bin_path, command, options, targets, startup_options,
  File "/home/benjamin/.cache/bazel/_bazel_benjamin/87896217ed058d0cf7ddf603fa041dc4/execroot/__main__/bazel-out/k8-fastbuild/bin/benchmark.runfiles/__main__/benchmark.py", line 266, in _single_run
    measurements['memory'],
KeyError: 'memory'
```

**Comment by joeleba** [comment]
This should be obsolete after #110.
