### ISSUE TITLE
Invoking the example from README fails

### ISSUE THREAD

**Issue by snazhmudinov** [bazelbuild/bazel-bench#158]
**Description of the problem / feature request:**

Trying to run the example benchmark from `README`, and it gives me the error:
```
ERROR: /Users/sherozn/.bazel-bench/project-clones/3915c08828952724cf3dcead4c416118/tools/build_rules/java_rules_skylark.bzl:59:39: invalid escape sequence: \.. Use '\\' to insert '\'.
ERROR: /Users/sherozn/.bazel-bench/project-clones/3915c08828952724cf3dcead4c416118/src/BUILD:140:11: error loading package 'src/java_tools/buildjar/java/com/google/devtools/build/buildjar/jarhelper': compilation of module 'tools/build_rules/java_rules_skylark.bzl' failed and referenced by '//src:embedded_tools_jdk_minimal_srcs'
ERROR: Analysis of target '//src:bazel' failed; build aborted:
INFO: Elapsed time: 0.051s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (4 packages loaded, 0 targets configured)
    currently loading: src/java_tools/buildjar/java/com/google/devtools/build/buildjar/jarhelper ... (2 packages)
    Fetching repository @local_config_cc_toolchains; starting
    Fetching repository @local_jdk; starting
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_sherozn/4e4b6bfdaf070146b8f266fb0b3ab2cc/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/benchmark.runfiles/__main__/benchmark.py", line 698, in <module>
    app.run(main)
  File "/private/var/tmp/_bazel_sherozn/4e4b6bfdaf070146b8f266fb0b3ab2cc/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/benchmark.runfiles/third_party/pypi__absl_py/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/private/var/tmp/_bazel_sherozn/4e4b6bfdaf070146b8f266fb0b3ab2cc/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/benchmark.runfiles/third_party/pypi__absl_py/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/private/var/tmp/_bazel_sherozn/4e4b6bfdaf070146b8f266fb0b3ab2cc/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/benchmark.runfiles/__main__/benchmark.py", line 621, in main
    bazel_bin_path = _build_bazel_binary(unit['bazel_commit'],
  File "/private/var/tmp/_bazel_sherozn/4e4b6bfdaf070146b8f266fb0b3ab2cc/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/benchmark.runfiles/__main__/benchmark.py", line 175, in _build_bazel_binary
    _exec_command(['bazel', 'build', '//src:bazel'], cwd=repo.working_dir)
  File "/private/var/tmp/_bazel_sherozn/4e4b6bfdaf070146b8f266fb0b3ab2cc/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/benchmark.runfiles/__main__/benchmark.py", line 61, in _exec_command
    return subprocess.run(
  File "/private/var/tmp/_bazel_sherozn/4e4b6bfdaf070146b8f266fb0b3ab2cc/external/python3_10_aarch64-apple-darwin/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'build', '//src:bazel']' returned non-zero exit status 1.
```

Command I'm trying to execute from the terminal:
```bash
bazel run :benchmark \
-- \
--project_source=https://github.com/bazelbuild/rules_cc.git \
--data_directory=/tmp/bazel-bench-data \
--verbose \
-- build //:all
```

**Comment by snazhmudinov** [comment]
I re-tried it again, and managed to make it work, however, i get exit code 2:
```
Starting local Bazel server and connecting to it...
E0808 13:52:18.150512 8488296576 logger.py:44] Bazel command failed with exit code 2
I0808 13:52:18.690765 8488296576 logger.py:34] Results of this run: wall: 0.101s, cpu 0.002s, system 0.000s, memory 16.000MB, exit_status: 2
I0808 13:52:18.690902 8488296576 logger.py:34] Executing Bazel command: bazel  clean --color=no
I0808 13:52:19.319098 8488296576 logger.py:34] Executing Bazel command: bazel  shutdown
```

**Comment by snazhmudinov** [comment]
I managed to get it work, eventually.
