### ISSUE TITLE
Error in path: Not a regular file: python3_10_x86_64-apple-darwin/WORKSPACE

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel-bench#173]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3521#018c5bca-c8f4-4692-b6ba-f2ceaaeb2094

Platform : MacOS

Logs:
```

(03:12:28) ERROR: An error occurred during the fetch of repository 'third_party':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_buildkite/4e9cc81b0b6cd04f715b7270e313d439/external/rules_python/python/pip_install/pip_repository.bzl", line 235, column 63, in _pip_repository_impl
		environment = _create_repository_execution_environment(rctx),
	File "/private/var/tmp/_bazel_buildkite/4e9cc81b0b6cd04f715b7270e313d439/external/rules_python/python/pip_install/pip_repository.bzl", line 158, column 37, in _create_repository_execution_environment
		_maybe_set_xcode_location_cflags(rctx, env)
	File "/private/var/tmp/_bazel_buildkite/4e9cc81b0b6cd04f715b7270e313d439/external/rules_python/python/pip_install/pip_repository.bzl", line 83, column 26, in _maybe_set_xcode_location_cflags
		rctx.path(Label("@{}//:WORKSPACE".format(rctx.attr.python_interpreter_target.workspace_name))).dirname,
Error in path: Not a regular file: /private/var/tmp/_bazel_buildkite/4e9cc81b0b6cd04f715b7270e313d439/external/python3_10_x86_64-apple-darwin/WORKSPACE
```

Steps:
```
git clone https://github.com/bazelbuild/bazel-bench.git 
git reset 656fdf243022f3cbadf2f7ce161a401212add6e6 --hard
export USE_BAZEL_VERSION=104a711ae1772be62b6034506d51c5fee486b589
bazel build //...
```

CC Greenteam @comius

**Comment by sgowroji** [comment]
We can close this issue as it is shows green now.
