### ISSUE TITLE
[Bazel CI] Build failed due to pip package hash mismatch for rules_python++pip+third_party_310_grpcio


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel-bench#185]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4162#01924649-7460-4f18-84d2-a94573035c93

 Platform: MacOS

 Logs: 
```
ERROR: no such package '@@rules_python++pip+third_party_310_grpcio//':
rules_python:whl_library(@@rules_python++pip+third_party_310_grpcio) FAIL: repo.execute: whl_library.ResolveRequirement(rules_python++pip+third_party_310_grpcio, grpcio==1.62.1): end: failure:
  command: /private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python++python+python_3_10_host/python -m python.private.pypi.whl_installer.wheel_installer --requirement grpcio==1.62.1 --isolated --extra_pip_args "{\"arg\":[]}" --pip_data_exclude "{\"arg\":[]}" --environment "{\"arg\":{}}"
  return code: 1
  working dir: <default: /private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python++pip+third_party_310_grpcio>
  timeout: 600
  environment:
PYTHONPATH="/private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python+:/private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python++internal_deps+pypi__build:/private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python++internal_deps+pypi__click:/private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python++internal_deps+pypi__colorama:/private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python++internal_deps+pypi__importlib_metadata:/private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python++internal_deps+pypi__installer:/private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python++internal_deps+pypi__more_itertools:/private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python++internal_deps+pypi__packaging:/private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python++internal_deps+pypi__pep517:/private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python++internal_deps+pypi__pip:/private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python++internal_deps+pypi__pip_tools:/private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python++internal_deps+pypi__pyproject_hooks:/private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python++internal_deps+pypi__setuptools:/private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python++internal_deps+pypi__tomli:/private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python++internal_deps+pypi__wheel:/private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python++internal_deps+pypi__zipp"
CPPFLAGS="-isysroot /Applications/Xcode15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -isystem /private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python++python+python_3_10_host/include/python3.10"
===== stdout start =====
Collecting grpcio==1.62.1 (from -r /tmp/tmpmcdwrnbd (line 1))
  Downloading grpcio-1.62.1-cp310-cp310-macosx_12_0_universal2.whl.metadata (4.0 kB)
Downloading grpcio-1.62.1-cp310-cp310-macosx_12_0_universal2.whl (10.0 MB)
   ━━━━━━━━                                 2.1/10.0 MB 1.0 MB/s eta 0:00:08
===== stdout end =====
===== stderr start =====
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    unknown package:
        Expected sha256 48611e4fa010e823ba2de8fd3f77c1322dd60cb0d180dc6630a7e157b205f7ea
             Got        2e2b530e6af37804941fa21c9818ca4906ba7807b30ca83133d9ec2147716527
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python++python+python_3_10_aarch64-apple-darwin/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python++python+python_3_10_aarch64-apple-darwin/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python+/python/private/pypi/whl_installer/wheel_installer.py", line 205, in <module>
    main()
  File "/private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python+/python/private/pypi/whl_installer/wheel_installer.py", line 190, in main
    subprocess.run(pip_args, check=True, env=env)
  File "/private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python++python+python_3_10_aarch64-apple-darwin/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/private/var/tmp/_bazel_buildkite/f5cc5bbf57aed7ab5e73ef558806a56a/external/rules_python++python+python_3_10_host/python', '-m', 'pip', '--isolated', 'wheel', '--no-deps', '-r', '/tmp/tmpmcdwrnbd']' returned non-zero exit status 1.
===== stderr end =====
``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/bazel-bench
git reset 5efc0e1f0a00d8cb1a8da09bd91949c81940e053  --hard
export USE_BAZEL_VERSION=a716fdf5c03c918daad557a0bec9ace74400ec2f
bazel test //... 
 ``` 
 CC Greenteam @mai93

**Comment by sgowroji** [comment]
As the CI is green we are closing this issue now.https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4571#0195ef88-06ad-4afa-8eae-797cf8b4ea47
